version: '3.8'

services:
  mariadb-columnstore:
    image: mariadb/columnstore:latest
    container_name: mcs_container
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=shoppers_db
      - MARIADB_USER=sonu
      - MARIADB_PASSWORD=Yunachan10
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      # Map to your project directory so both container and host can access
      - /home/sonu/mlop_final/mlflow_data:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0


  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/opt/artifacts
      - ./mlruns:/mlflow
    environment:
      - DB_CONN=mariadb+pymysql://sonu:Yunachan10@mariadb-columnstore:3306/shoppers_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ARTIFACT_DIR=/opt/artifacts
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mariadb-columnstore
      - redis
      - mlflow
    restart: unless-stopped

  streamlit:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/opt/artifacts
    environment:
      - FASTAPI_URL=http://fastapi:8000
      - ARTIFACT_DIR=/opt/artifacts
    depends_on:
      - fastapi
    restart: unless-stopped

volumes:
  redis_data:
  mariadb_data:
